#![no_std]

//! Escrow contract.
//!
//! Orchestrates the escrow lifecycle and delegates all custody of funds to the
//! PaymentVault contract through Soroban cross-contract invocation. The vault
//! is configured at initialization; this contract calls `deposit`, `release`
//! and `refund` on it. The frontend only ever talks to this contract.

mod errors;
mod events;
mod storage;
mod types;

#[cfg(test)]
mod test;

pub use errors::EscrowError;
pub use types::{Escrow, Status};

use soroban_sdk::{contract, contractclient, contractimpl, Address, Env, String, Vec};

/// Typed client for the PaymentVault contract. Generated by `#[contractclient]`
/// and used to perform real cross-contract calls from the Escrow contract.
#[contractclient(name = "VaultClient")]
pub trait PaymentVaultInterface {
    fn deposit(env: Env, escrow_id: u64, from: Address, amount: i128);
    fn release(env: Env, escrow_id: u64, to: Address);
    fn refund(env: Env, escrow_id: u64, to: Address);
}

#[contract]
pub struct EscrowContract;

#[contractimpl]
impl EscrowContract {
    /// One-time configuration: bind this contract to its PaymentVault and asset.
    pub fn initialize(env: Env, vault: Address, token: Address) -> Result<(), EscrowError> {
        if storage::is_initialized(&env) {
            return Err(EscrowError::AlreadyInitialized);
        }
        storage::set_vault(&env, &vault);
        storage::set_token(&env, &token);
        Ok(())
    }

    /// Register a new escrow agreement (status `Pending`). No funds move yet.
    pub fn create_escrow(
        env: Env,
        buyer: Address,
        seller: Address,
        amount: i128,
        description: String,
    ) -> Result<u64, EscrowError> {
        buyer.require_auth();

        let token = storage::get_token(&env)?;
        if amount <= 0 {
            return Err(EscrowError::InvalidAmount);
        }
        if buyer == seller {
            return Err(EscrowError::SameBuyerSeller);
        }

        let id = storage::get_count(&env);
        let escrow = Escrow {
            id,
            buyer: buyer.clone(),
            seller: seller.clone(),
            token,
            amount,
            description,
            status: Status::Pending,
            created_at: env.ledger().timestamp(),
        };

        storage::save_escrow(&env, &escrow);
        storage::set_count(&env, id + 1);
        events::created(&env, id, &buyer, &seller, amount);
        Ok(id)
    }

    /// Buyer locks funds. Cross-contract call: `PaymentVault.deposit`.
    pub fn deposit_funds(env: Env, escrow_id: u64) -> Result<(), EscrowError> {
        let mut escrow = storage::get_escrow(&env, escrow_id)?;
        escrow.buyer.require_auth();

        if escrow.status != Status::Pending {
            return Err(EscrowError::InvalidStatus);
        }

        let vault = storage::get_vault(&env)?;
        VaultClient::new(&env, &vault).deposit(&escrow_id, &escrow.buyer, &escrow.amount);

        escrow.status = Status::Funded;
        storage::save_escrow(&env, &escrow);
        events::funded(&env, escrow_id, escrow.amount);
        Ok(())
    }

    /// Seller confirms delivery (`Funded` -> `Delivered`).
    pub fn mark_delivered(env: Env, escrow_id: u64) -> Result<(), EscrowError> {
        let mut escrow = storage::get_escrow(&env, escrow_id)?;
        escrow.seller.require_auth();

        if escrow.status != Status::Funded {
            return Err(EscrowError::InvalidStatus);
        }

        escrow.status = Status::Delivered;
        storage::save_escrow(&env, &escrow);
        events::delivered(&env, escrow_id, &escrow.seller);
        Ok(())
    }

    /// Buyer releases payment. Cross-contract call: `PaymentVault.release`.
    pub fn release_payment(env: Env, escrow_id: u64) -> Result<(), EscrowError> {
        let mut escrow = storage::get_escrow(&env, escrow_id)?;
        escrow.buyer.require_auth();

        if escrow.status != Status::Funded && escrow.status != Status::Delivered {
            return Err(EscrowError::InvalidStatus);
        }

        let vault = storage::get_vault(&env)?;
        VaultClient::new(&env, &vault).release(&escrow_id, &escrow.seller);

        escrow.status = Status::Completed;
        storage::save_escrow(&env, &escrow);
        events::completed(&env, escrow_id, &escrow.seller, escrow.amount);
        Ok(())
    }

    /// Buyer refunds before release. Cross-contract call: `PaymentVault.refund`.
    pub fn refund_payment(env: Env, escrow_id: u64) -> Result<(), EscrowError> {
        let mut escrow = storage::get_escrow(&env, escrow_id)?;
        escrow.buyer.require_auth();

        if escrow.status != Status::Funded && escrow.status != Status::Delivered {
            return Err(EscrowError::InvalidStatus);
        }

        let vault = storage::get_vault(&env)?;
        VaultClient::new(&env, &vault).refund(&escrow_id, &escrow.buyer);

        escrow.status = Status::Refunded;
        storage::save_escrow(&env, &escrow);
        events::refunded(&env, escrow_id, &escrow.buyer, escrow.amount);
        Ok(())
    }

    pub fn get_escrow(env: Env, escrow_id: u64) -> Result<Escrow, EscrowError> {
        storage::get_escrow(&env, escrow_id)
    }

    /// All escrows ever created, oldest first.
    pub fn list_escrows(env: Env) -> Vec<Escrow> {
        let count = storage::get_count(&env);
        let mut escrows = Vec::new(&env);
        for id in 0..count {
            if let Some(escrow) = storage::try_get_escrow(&env, id) {
                escrows.push_back(escrow);
            }
        }
        escrows
    }

    pub fn get_vault(env: Env) -> Result<Address, EscrowError> {
        storage::get_vault(&env)
    }
}
